name: ngs-analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - fire
  - glob2
  - ipykernel
  - natsort
  - pandas
  - pandera
  - parse
  - pyarrow
  - python-levenshtein
  - python-slugify
  - pyyaml
  - regex
  - seaborn
  - tqdm
